<% jruby = defined?(JRUBY_VERSION)  %>

<% if jruby == "constant" %>
test:
  adapter: jdbcmysql
  host: localhost
  database: leihs2_test
  encoding: utf8
  username: root
  password:

<% else %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: leihs2_test
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

<% end %>
